version: '3.1'

services:
  db:
    image: mysql:8.2

    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: PAYMYBUDDY
      MYSQL_ROOT_PASSWORD: root
    ports:
        - "3307:3306"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8080"
